### ISSUE TITLE
Command to show accounts linked to user

### ISSUE THREAD

**Issue by mikylucky** [KaluNight/Zoe-Discord-Bot#378]
Hi, would be nice to have an command to show the accounts linked to a specific Discord user

Something like

`>show accounts @username`

**Comment by KaluNight** [comment]
Hello @mikylucky!

Yup, great QOL suggestion. Pretty easy to do. I work on it.

**Comment by KaluNight** [comment]
Your suggestion has been implemented today. You can test it now. Thanks you for it!
