### ISSUE TITLE
add account adds account to the wrong user

### ISSUE THREAD

**Issue by mikylucky** [KaluNight/Zoe-Discord-Bot#380]
When I try to add an account to a user, the account gets added to me instead of the tagged user

The command I use is `>add account @user (region) (account)`

**Comment by KaluNight** [comment]
Hello @mikylucky 

I work on the bug fix, i let you know when this is fixed.

**Comment by KaluNight** [comment]
Bug fix deployed. Should be good. Thanks you for your patience!
