### ISSUE TITLE
Question: Is there a way to change the Information Panel's refresh rate?

### ISSUE THREAD

**Issue by T145** [KaluNight/Zoe-Discord-Bot#432]
It seems to be set at 60 minutes but I'd like to make it more frequent if possible.

**Comment by theflamehd** [comment]
Hey there @T145 ,
Zoe refreshs each server one by one. The refresh rate is an estimation of how many time this will take to refresh all servers. There is no option to make it more frequent.

Read more here: https://wiki.zoe-discord-bot.ch/en/terms/refresh-mode

A rework for these channels is planned vor v1.12.1. You can join our Discord server to get notified on whats going on: https://discord.gg/4Rxrzsxb7d

~theflamehd

**Comment by KaluNight** [comment]
Hello @T145 

It was actually working like this until an update was done some time ago, this page needs to be redone. Now effectively all servers are refreshed at least once an hour and there is no way to increase it for the moment in a stable way.

What you can do is to be online and activate Discord Presence, Zoe will detect the start and end of your game and refresh directly at the right time. This is enough for most cases.

I'm planning to rework it to make it more intelligent with a system that detects the hours of activity per account and refresh them more often in these periods.

This update will not happen immediately as there are other priorities at the moment, but it is planned and will happen one day.
